# Generated by Django 4.2.2 on 2025-10-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="user",
            name="department",
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True, verbose_name="Адрес"),
        ),
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("M", "Мужской"), ("F", "Женский"), ("O", "Другой")],
                default="O",
                max_length=1,
                verbose_name="Пол",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="medical_history",
            field=models.TextField(blank=True, verbose_name="Медицинская история"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
    ]
