# Generated by Django 4.2.2 on 2025-10-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_managers_remove_user_department_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="middle_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="Отчество"),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("M", "Мужской"), ("F", "Женский")],
                default="O",
                max_length=1,
                verbose_name="Пол",
            ),
        ),
    ]
