services:
  # PostgreSQL
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-medical_lab_db}
      POSTGRES_USER: ${POSTGRES_USER:-medical_lab_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-medical_lab_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - medical_lab_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-medical_lab_user}"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Redis
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - habits_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Django Application
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 --workers 3 config.wsgi:application"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    environment:
      - DEBUG=${DEBUG:-False}
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=${POSTGRES_DB:-medical_lab_db}
      - DB_USER=${POSTGRES_USER:-medical_lab_user}
      - DB_PASSWORD=${POSTGRES_PASSWORD:-medical_lab_password}
      - DB_HOST=postgres
      - DB_PORT=5432
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1,0.0.0.0,158.160.12.110}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - habits_network

  # Celery Worker
  celery_worker:
    build: .
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - DEBUG=${DEBUG:-False}
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=${POSTGRES_DB:-medical_lab_db}
      - DB_USER=${POSTGRES_USER:-medical_lab_user}
      - DB_PASSWORD=${POSTGRES_PASSWORD:-medical_lab_password}
      - DB_HOST=postgres
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
      - web
    networks:
      - habits_network

  # Celery Beat
  celery_beat:
    build: .
    command: celery -A config beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    environment:
      - DEBUG=${DEBUG:-False}
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=${POSTGRES_DB:-medical_lab_db}
      - DB_USER=${POSTGRES_USER:-medical_lab_user}
      - DB_PASSWORD=${POSTGRES_PASSWORD:-medical_lab_password}
      - DB_HOST=postgres
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
      - web
    networks:
      - habits_network

  # Nginx
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - web
    networks:
      - medical_lab_network

volumes:
  postgres_data:
  redis_data:
  static_volume:

networks:
  habits_network:
    driver: bridge
