# Generated by Django 4.2.2 on 2025-10-03 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("medical_lab", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="generated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создатель отчета",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_patients",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создатель карточки",
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="analysis_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analyses",
                to="medical_lab.analysistype",
                verbose_name="Тип анализа",
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="lab_technician",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="performed_analyses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Лаборант",
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analyses",
                to="medical_lab.patient",
                verbose_name="Пациент",
            ),
        ),
    ]
